language: node_js
node_js:
 - "0.10"
before_script:
 - npm install -g grunt-cli; chmod u+x deploy-to-gh-pages.sh; grunt build
script: ./deploy-to-gh-pages.sh
env:
 global:
  - GH_REF: github.com/RactiveJS/docs.ractivejs.org.git
  - secure: AXOggwbE9d5bcLlAXQrpjc7EQz0qgpkYI8JICzNFwh9I7pqDy1BAg1nC8nc0c1Pyd/HTZH+4hkSO3vjuffTEdV7Nb/gEqo2Wu8lnB/NfAx6bNvMPK0rp54qc9kLr93m0i0ttDDnT3XoLdY7c9T3AFWHTF4c8y9ihvAqx+f4LaB8=
